# main.py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
import os

from models.schemas import CareerRequest, CareerResponse, HealthResponse

# Load environment variables from .env
load_dotenv()

# Create the FastAPI application
app = FastAPI(
    title="AI Career Coach API",
    description="Multi-agent career coaching system powered by CrewAI and Groq",
    version="1.0.0",
)

# CORS — allows the Next.js frontend to call this API
# During development, allow all origins. In production, restrict to your Vercel URL.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],           # Replace "*" with Vercel URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", response_model=HealthResponse, tags=["System"])
async def health_check():
    """
    GET /health
    UptimeRobot pings this every 5 minutes to keep Render from sleeping.
    Always returns 200 OK with a status message.
    """
    return HealthResponse(
        status="ok",
        message="Career Coach API is running"
    )


@app.post("/career/analyze", response_model=CareerResponse, tags=["Career"])
async def analyze_career(request: CareerRequest):
    """
    POST /career/analyze
    Main endpoint. On Day 2: returns placeholder text.
    On Day 5: runs the full 3-agent CrewAI pipeline and returns real analysis.

    FastAPI automatically:
    - Validates the incoming JSON against CareerRequest
    - Returns a 422 error if validation fails
    - Serializes the response using CareerResponse
    - Documents this endpoint in Swagger UI at /docs
    """

    # ── Day 2: Placeholder response ──────────────────────────────────────────
    # This confirms the endpoint works end-to-end before agents are wired in.
    # You will replace this entire block on Day 5 with:
    #   result = crew_service.run_crew(request.skills, request.goal, request.experience)
    #   return CareerResponse(**result)

    placeholder_skill_gaps = (
        f"[PLACEHOLDER - Day 2] Skill gap analysis for '{request.goal}' role. "
        f"User has: {request.skills}. "
        f"Experience: {request.experience}. "
        f"Real analysis will be here after agents are wired in on Day 5."
    )

    placeholder_career_paths = (
        f"[PLACEHOLDER - Day 2] Three career paths toward '{request.goal}' "
        f"will be generated by the Market Advisor agent on Day 4."
    )

    placeholder_roadmap = (
        f"[PLACEHOLDER - Day 2] An 8-week learning roadmap will be generated "
        f"by the Roadmap Planner agent using real course data from ChromaDB on Day 9."
    )

    return CareerResponse(
        skill_gaps=placeholder_skill_gaps,
        career_paths=placeholder_career_paths,
        roadmap=placeholder_roadmap,
        message="Placeholder response — agents will be wired in on Day 5"
    )